[project]
name = "mss-autoteam"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "dolphin-memory-engine==1.3.0",
    "keyboard==0.13.5",
    "mii-lib==0.2.0",
    "PyGetWindow==0.0.9",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.18.0",
]
